---
- name: Install and configure the necessary dependencies
  yum: name={{ item }} state=present
  with_items:
    - curl
    - openssh-server
    - openssh-clients
    - postfix
    - cronie

- name: Start Postfix
  service: name=postfix state=started enabled=yes

# WARNING: this command create new iptables rules only for server without iptables config
# - name: execute Lokkit 
#   shell: lokkit -s http -s ssh

# Role with proxy
# - name: Add the GitLab script
#   copy: src=script.rmp.sh dest=/home/{{ host_user }} mode=0775
# - name: Execute bash
#   shell: bash /home/{{ host_user }}/script.rmp.sh

# Role without proxy
- name: Add the GitLab package server
  shell: curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh | sudo bash

- name: Install GitLab
  yum: name={{ item }} state=present
  with_items:
    - gitlab-ce

- name: Configure and start GitLab
  shell: gitlab-ctl reconfigure
